### ISSUE TITLE
found error on code 

### ISSUE THREAD

**Issue by A-Kits** [paysbuy/psb-magento1#1]
Parse error: syntax error, unexpected '[', expecting ')' in yourwebsite.com/public_html/app/code/local/Paysbuy/Psb/Model/Psb.php on line 14

**Comment by jon-paysbuy** [comment]
This is due to using an old version of PHP. Magento 1 requires PHP 5.4 or above - http://devdocs.magento.com/guides/m1x/system-requirements.html

Upgrading PHP will solve this issue.
